# Generated by Django 3.2.9 on 2021-11-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211129_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabel',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
