# Generated by Django 3.2.9 on 2022-03-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_tabel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabel',
            name='host',
        ),
        migrations.RemoveField(
            model_name='tabel',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Tabel',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
